---
title: "Lab 4"
author: "Akash Agrawal Bejarano"
date: "1/17/2023"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1
```{r}
library(tidyverse)
x <- list(2, 4, 5, 9, 1)
y <- list(8, 7, 2, 8, 3)
z <- list(1, 8, 5, 4, 2)
pmap_dbl(list(x,y,z), function(first, second, third) (first + second + third)^2)
```


## Question 2

```{r}
tribble( ~Student,  ~Gender,    ~Salary,
                   "John",   "Male",       65000,
                   "Alice",  "Female",    73000,
                    "Juan",   "Male",       66000,
                    "Beth",  "Female",    71500,
                    "Denise", "Female",  82000
) -> table
table %>%   pmap_chr(~ str_glue("{..1} who is  {..2}, has a salary that is {..3} dollars per year."))
```

## Question 3

```{r}
matrix1 = matrix(nrow=5, ncol=5)
for(i in 1:nrow(matrix1)){
  for(j in 1:ncol(matrix1)){
    matrix1[i,j] = i+j           
  }}
print(matrix1)
```

## Question 4

```{r}
for(i in 1:20){
  if(i != 5 & i != 10){
    print(i)
  }
}
```